name: auto_ci

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10"]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Display working directory
        run: |
          pwd
          java -version

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'       # You can choose 'temurin', 'zulu', etc.
          java-version: '17'          # Specify your desired JDK version
          cache: 'maven'     
      
      - name: install os lib
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libncurses5  

      - name: Set up Python and cache dependencies
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt

      - name: Install dependencies
        shell: bash
        run: |
          python --version
          pip install .
          pip install pytest PyMySQL

      - name: Run tests
        run: |
          pytest
